name       : syslinux
version    : 6.03
release    : 5
source     :
    - https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.xz : 26d3986d2bea109d5dc0e4f8c4822a459276cf021125e8c9f23c3cca5d8c850e
license    : GPL-2.0
summary    : Lightweight bootloaders
description: |
    The Syslinux Project covers lightweight bootloaders for MS-DOS FAT filesystems (SYSLINUX), network booting (PXELINUX), bootable "El Torito" CD-ROMs (ISOLINUX), and Linux ext2/ext3/ext4 or btrfs filesystems (EXTLINUX). The project also includes MEMDISK, a tool to boot legacy operating systems (such as DOS) from nontraditional media; it is usually used in conjunction with PXELINUX and ISOLINUX.
ccache     : no
setup      : |
    %patch -p1 < $pkgfiles/0005-load-linux-correct-type.patch
    %patch -p1 < $pkgfiles/0006-load-linux-protected-mode.patch
    %patch -p1 < $pkgfiles/0035-SYSAPPEND-Fix-space-stripping.patch
    %patch -p1 < $pkgfiles/fix-alignment-change-gcc-5.patch
    %patch -p1 < $pkgfiles/dont-guess-section-alignment.patch
build      : |
    # syslinux being a delicate flower.
    unset LDFLAGS
    unset CFLAGS
    unset CXXFLAGS
    %make bios
install    : |
    unset LDFLAGS
    unset CFLAGS
    unset CXXFLAGS
    %make_install INSTALLROOT="$installdir" SBINDIR=/usr/bin MANDIR=/usr/share/man AUXDIR=%libdir%/syslinux
